[phases.setup]
nixPkgs = ['python311', 'python311.pkgs.pip', 'postgresql']
cmds = ['python -m venv /opt/venv']

[phases.install]
cmds = [
    'source /opt/venv/bin/activate',
    'pip install --upgrade pip setuptools wheel',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = ['python manage.py collectstatic --noinput']

[start]
cmd = 'gunicorn portfolio_backend.wsgi:application'
stopSignal = "SIGINT"

[variables]
PYTHONUNBUFFERED = "1"
PATH = "/opt/venv/bin:${PATH}" 