# Generated by Django 5.1.7 on 2025-03-19 05:57

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=api.models.profile_image_path)),
                ('display_name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='例: フルスタックエンジニア', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='自己紹介/自己PR')),
                ('specialty', models.CharField(blank=True, help_text='専門分野', max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('email_public', models.EmailField(blank=True, help_text='公開用メールアドレス', max_length=254)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('qiita_username', models.CharField(blank=True, max_length=100)),
                ('twitter_username', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('resume', models.FileField(blank=True, help_text='職務経歴書PDF', null=True, upload_to=api.models.resume_path)),
                ('portfolio_slug', models.SlugField(help_text='URLに使用する一意の文字列', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(choices=[(1, '初級'), (2, '中級'), (3, '上級'), (4, 'エキスパート'), (5, 'マスター')], default=1)),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=api.models.skill_icon_path)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.skillcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.userprofile')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project_thumbnails/')),
                ('project_url', models.URLField(blank=True, help_text='プロジェクトのURL')),
                ('github_url', models.URLField(blank=True, help_text='GitHubリポジトリのURL')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='注目プロジェクトとして表示')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies_used', models.ManyToManyField(related_name='projects', to='api.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.userprofile')),
            ],
            options={
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('skills_used', models.ManyToManyField(blank=True, related_name='work_experiences', to='api.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='api.userprofile')),
            ],
            options={
                'ordering': ['-current', '-end_date', '-start_date'],
            },
        ),
    ]
