# Generated by Django 5.1.7 on 2025-03-24 16:27

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='education',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='ポートフォリオでの表示/非表示'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text='ポートフォリオで強調表示するスキル'),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='skill_categories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_access_token',
            field=models.CharField(blank=True, help_text='GitHub連携用アクセストークン', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qiita_access_token',
            field=models.CharField(blank=True, help_text='Qiita連携用アクセストークン', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='db_used',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='frameworks_used',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='languages_used',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='os_used',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='process_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='process_roles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='role_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='portfolio_slug',
            field=models.SlugField(default=api.models.generate_unique_portfolio_id, help_text='URLに使用する一意の文字列', unique=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='skillcategory',
            unique_together={('name', 'user')},
        ),
        migrations.CreateModel(
            name='GitHubCommitStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_count_total', models.IntegerField(default=0, help_text='総コミット数')),
                ('commit_count_last_year', models.IntegerField(default=0, help_text='過去1年のコミット数')),
                ('contributions_by_month', models.JSONField(default=dict, help_text='月ごとのコントリビューション数')),
                ('languages_used', models.JSONField(default=dict, help_text='使用言語の割合')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='最終更新日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_stats', to='api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'GitHub Commit Stats',
            },
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='リポジトリ名', max_length=255)),
                ('full_name', models.CharField(help_text='フルリポジトリ名（ユーザー名/リポジトリ名）', max_length=255)),
                ('html_url', models.URLField(help_text='GitHubリポジトリURL')),
                ('description', models.TextField(blank=True, help_text='リポジトリの説明', null=True)),
                ('language', models.CharField(blank=True, help_text='主要言語', max_length=100, null=True)),
                ('stargazers_count', models.IntegerField(default=0, help_text='スター数')),
                ('forks_count', models.IntegerField(default=0, help_text='フォーク数')),
                ('open_issues_count', models.IntegerField(default=0, help_text='オープンなイシュー数')),
                ('watchers_count', models.IntegerField(default=0, help_text='ウォッチャー数')),
                ('created_at', models.DateTimeField(help_text='リポジトリ作成日')),
                ('updated_at', models.DateTimeField(help_text='リポジトリ更新日')),
                ('pushed_at', models.DateTimeField(help_text='最終プッシュ日')),
                ('featured', models.BooleanField(default=False, help_text='ポートフォリオで特集するかどうか')),
                ('topics', models.JSONField(blank=True, default=list, help_text='トピックタグ', null=True)),
                ('is_fork', models.BooleanField(default=False, help_text='フォークかどうか')),
                ('is_private', models.BooleanField(default=False, help_text='プライベートリポジトリかどうか')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repositories', to='api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'GitHub Repositories',
                'ordering': ['-featured', '-pushed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('requirements', '要件定義'), ('basic_design', '基本設計'), ('detailed_design', '詳細設計'), ('implementation', '実装'), ('testing', '試験'), ('deployment', 'デプロイ/リリース'), ('operation', '運用/保守')], max_length=50)),
                ('experience_count', models.PositiveIntegerField(default=0, help_text='担当した回数')),
                ('description', models.TextField(blank=True, help_text='この工程での経験やスキルについての説明')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_experiences', to='api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Process Experiences',
                'ordering': ['process_type'],
                'unique_together': {('user', 'process_type')},
            },
        ),
        migrations.CreateModel(
            name='QiitaArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(help_text='Qiita記事ID', max_length=255)),
                ('title', models.CharField(help_text='記事タイトル', max_length=255)),
                ('url', models.URLField(help_text='記事URL')),
                ('likes_count', models.IntegerField(default=0, help_text='いいね数')),
                ('stocks_count', models.IntegerField(default=0, help_text='ストック数')),
                ('comments_count', models.IntegerField(default=0, help_text='コメント数')),
                ('created_at', models.DateTimeField(help_text='記事作成日')),
                ('updated_at', models.DateTimeField(help_text='記事更新日')),
                ('tags', models.JSONField(blank=True, default=list, help_text='記事のタグ', null=True)),
                ('body_md', models.TextField(blank=True, help_text='記事本文(Markdown)', null=True)),
                ('body_html', models.TextField(blank=True, help_text='記事本文(HTML)', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='ポートフォリオで特集するかどうか')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qiita_articles', to='api.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Qiita Articles',
                'ordering': ['-is_featured', '-created_at'],
                'unique_together': {('user', 'article_id')},
            },
        ),
    ]
