# Generated by Django 5.1.7 on 2025-04-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_skillcategory_options_education_is_visible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='education',
            name='field_of_study',
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(help_text='学校名（学科）', max_length=200),
        ),
    ]
